version: "3"

services:
  apache:
    build: ./Apache-01
    ports:
      - "80:80"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./Apache-01/webroot:/var/www/html
      - ./Apache-01/webroot2:/var/www/html2
      - ./Apache-01/etc/httpd/conf.d/:/etc/httpd/conf.d
    networks:
      train_net:
        ipv4_address: 172.30.0.2
    dns:
      - 172.30.0.3

  bind:
    build: ./bind-01
    ports:
      - "53:53/udp"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./Bind-01/etc/named.conf:/etc/named.conf
      - ./Bind-01/etc/myzones.zones:/etc/myzones.zones
      - ./Bind-01/var/named/zones_master:/var/named/zones_master
    networks:
      train_net:
        ipv4_address: 172.30.0.3
    dns:
      - 127.0.0.1

  ldap-server:
    image: osixia/openldap:latest
    container_name: ldap-host
    volumes:
      - ./ldap-01/DB:/var/lib/ldap
      - ./ldap-01/slapd.d:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: "training"
      LDAP_DOMAIN: "training.test"
      LDAP_ADMIN_PASSWORD: "Zaq1Xsw2"
    networks:
      train_net:
        ipv4_address: 172.30.0.4
    dns:
      - 172.30.0.3

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap-server:ldap"
    networks:
      train_net:
        ipv4_address: 172.30.0.5
    dns:
      - 172.30.0.3

networks:
  train_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
